version: '3'
services:
  app:
    container_name: myretail
    image: myretail
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
  redis:
    container_name: redis
    image: redis
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"