spring:
  application:
    name: myretail
  redis:
    host: localhost
    port: 6379

server:
  port: 8080
  servlet:
    context-path: /myretail

product-description:
  api:
    host: http://localhost:8080
    productDescription: /myretail/products/description/{productId}